// Bundle js/vault-app.mjs -> src/vault.js (checked in; served by the wasm).
//
// Everything the page runs is vendored at build time - scripts/nan-vault.mjs
// (the protocol), viem (chain access), @tinfoilsh/verifier (attestation) -
// so the served app has NO runtime CDN dependency: a script fetched at run
// time could exfiltrate the wallet-derived vault key or an unsealed VEK.
//
// Run from anywhere: node wasm/apps/vault/js/build.mjs
// (deps resolve from the repo-root node_modules; esbuild is a root devDep)
import { build } from "esbuild";
import { fileURLToPath } from "node:url";

const here = (p) => fileURLToPath(new URL(p, import.meta.url));

const r = await build({
  entryPoints: [here("./vault-app.mjs")],
  outfile: here("../src/vault.js"),
  bundle: true,
  minify: true,
  format: "iife",
  platform: "browser",
  target: "es2020",
  // nan-vault.mjs lazily imports node:fs/child_process in its node-only CLI
  // paths, and the verifier lazily imports zlib as its no-DecompressionStream
  // fallback (every browser has DecompressionStream); keep those imports
  // external so they never execute in the browser.
  external: ["node:*", "zlib"],
  define: {
    "process.env.NODE_ENV": '"production"',
    // nan-vault.mjs's run-as-CLI guard reads process.argv at module load; in
    // the browser there is no process - pin the guard to a constant miss.
    "process.argv": "[]",
    "import.meta.url": '""',
  },
  logLevel: "info",
  banner: { js: "/* generated by js/build.mjs - DO NOT EDIT; edit js/vault-app.mjs and rebuild */" },
});
if (r.errors.length) process.exit(1);
